server:
  port: 5678 
spring:
  zipkin:
    baseUrl: http://localhost:9411/ 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolexam
    username: root
    password:
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
  file.name: logs/application-debug.log
  level:
    org.springframework.web: ERROR
    com.schoolexam: INFO
    org.hibernate: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
resilience4j:
  retry:
    retry-aspect-order: 2
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
         - org.springframework.web.client.RestClientException
        ignore-exceptions:
         - com.schoolexam.exception.IgnoreException
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      myCircuitBreaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60 
        failure-rate-threshold: 60